import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const TABLES = [
  "departments", "employees", "categories", "suppliers", "customers",
  "customer_addresses", "products", "promotions", "orders", "order_items",
  "inventory_transactions", "product_reviews", "sales_targets", "support_tickets",
];

function parseArgs(argv) {
  const values = new Map();
  for (let index = 0; index < argv.length; index += 2) values.set(argv[index], argv[index + 1]);
  const input = values.get("--input");
  const output = values.get("--output");
  if (!input || !output) throw new Error("Usage: node scripts/csv-to-d1.mjs --input <csv-directory> --output <seed.sql>");
  return { input: resolve(input), output: resolve(output) };
}

function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;
  for (let index = 0; index < text.length; index += 1) {
    const character = text[index];
    if (quoted && character === '"' && text[index + 1] === '"') { field += '"'; index += 1; continue; }
    if (character === '"') { quoted = !quoted; continue; }
    if (!quoted && character === ",") { row.push(field); field = ""; continue; }
    if (!quoted && (character === "\n" || character === "\r")) {
      if (character === "\r" && text[index + 1] === "\n") index += 1;
      row.push(field); field = "";
      if (row.some((value) => value.length > 0)) rows.push(row);
      row = [];
      continue;
    }
    field += character;
  }
  if (quoted) throw new Error("CSV contains an unterminated quoted field.");
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function identifier(value) {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/u.test(value)) throw new Error(`Unsafe CSV column name: ${value}`);
  return `"${value}"`;
}

function sqlValue(value) {
  if (value === "\\N") return "NULL";
  if (/^(?:true|false)$/iu.test(value)) return value.toLowerCase() === "true" ? "1" : "0";
  return `'${value.replaceAll("'", "''")}'`;
}

async function main() {
  const { input, output } = parseArgs(process.argv.slice(2));
  const statements = ["-- Generated by csv-to-d1.mjs. Import into an empty D1 database."];
  let totalRows = 0;
  for (const table of TABLES) {
    const csvPath = join(input, `${table}.csv`);
    let content;
    try { content = await readFile(csvPath, "utf8"); } catch (error) {
      if (error?.code === "ENOENT") continue;
      throw error;
    }
    const rows = parseCsv(content.replace(/^\uFEFF/u, ""));
    if (rows.length === 0) continue;
    const columns = rows[0].map(identifier);
    for (const [index, values] of rows.slice(1).entries()) {
      if (values.length !== columns.length) throw new Error(`${table}.csv row ${index + 2} has ${values.length} fields; expected ${columns.length}.`);
      statements.push(`INSERT INTO "${table}" (${columns.join(", ")}) VALUES (${values.map(sqlValue).join(", ")});`);
      totalRows += 1;
    }
  }
  if (totalRows === 0) throw new Error("No CSV data rows were found in the input directory.");
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, `${statements.join("\n")}\n`, "utf8");
  process.stdout.write(`Generated ${totalRows} D1 insert statements at ${output}\n`);
}

await main();

